const ADD_GITHUB_REPOS = 'ADD_GITHUB_REPOS';
const CLEAR_GITHUB_REPOS = 'CLEAR_GITHUB_REPOS';
const FAILURE_TO_GET_GITHUB_REPOS = 'FAILURE_TO_GET_GITHUB_REPOS';

module.exports = {
	ADD_GITHUB_REPOS: ADD_GITHUB_REPOS,
	CLEAR_GITHUB_REPOS: CLEAR_GITHUB_REPOS,
	FAILURE_TO_GET_GITHUB_REPOS: FAILURE_TO_GET_GITHUB_REPOS,
};
