const ADD_GITHUB_REPOS = 'ADD_GITHUB_REPOS';
const FAILURE_TO_GET_GITHUB_REPOS = 'FAILURE_TO_GET_GITHUB_REPOS';
const FORCE_REFRESH_GITHUB_REPOS = 'FORCE_REFRESH_GITHUB_REPOS';

module.exports = {
	/**
	 * GITHUB
	 */
	ADD_GITHUB_REPOS: ADD_GITHUB_REPOS,
	FORCE_REFRESH_GITHUB_REPOS: FORCE_REFRESH_GITHUB_REPOS,
	FAILURE_TO_GET_GITHUB_REPOS: FAILURE_TO_GET_GITHUB_REPOS
};
